name: Deploy Bot to vps

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy-bot
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy-bot/leagueTrackingBot
            git pull origin main
            docker compose up -d --build